version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  allow:
  - dependency-type: 
- package-ecosystem: docker
  directory: /devopsloft
  schedule:
    interval: daily
  allow:
  - dependency-type: all