version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: /devopsloft/app
  schedule:
    interval: weekly
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: /devopsloft/bakery
  schedule:
    interval: weekly
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: /devopsloft/certbot
  schedule:
    interval: weekly
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: /devopsloft/spinner
  schedule:
    interval: weekly
  allow:
  - dependency-type: all
  