version: "3.7"
services:
  db:
    image: devopsloft/db
    build: 
      context: .
      dockerfile: db_s2i/Dockerfile
    container_name: db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - 3306:3306
    restart: always

  app:
    image: devopsloft/app
    build:
      context: .
      dockerfile: app_s2i/Dockerfile
      args:
        APP_GUEST_PORT: $APP_GUEST_PORT
    container_name: app
    environment:
      - STATCODES
      - ENVIRONMENT
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - APP_GUEST_PORT
      - PYTHONPATH=$$PYTHONPATH:/modules
      - VAULT_ADDR=http://vault:$VAULT_GUEST_PORT
    ports:
      - 3000:3000
    restart: always

  vault:
    image: vault:1.1.2
    container_name: vault

    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  web:
    image: devopsloft/web
    build:
      context: .
      dockerfile: web_s2i/Dockerfile
      args:
        WEB_HOST_PORT: 5000
        WEB_HOST_SECURE_PORT: 8443
        APP_HOST_PORT: 3000
    container_name: web
    ports:
      - 5000:5000
      - 8443:8443
    restart: always
