version: "3"
services:
  db:
    image: ${NAMESPACE:-devopsloft}/db
    build: 
      context: .
      dockerfile: devopsloft/db/Dockerfile
    container_name: db
    environment:
      - SERVICE_NAME=db
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - 3306:3306
    restart: always

  app:
    image: ${NAMESPACE:-devopsloft}/app
    build:
      context: .
      dockerfile: devopsloft/app/Dockerfile
      args:
        - ENVIRONMENT
    container_name: app
    environment:
      - SERVICE_NAME=app
      - PYTHONPATH=$$PYTHONPATH:/home/modules
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - 3000:3000
    links:
      - db
    restart: always

  vault:
    image: ${NAMESPACE:-devopsloft}/vault
    build:
      context: .
      dockerfile: devopsloft/vault/Dockerfile
    container_name: vault
    environment:
      - SERVICE_NAME=vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  web:
    image: ${NAMESPACE:-devopsloft}/web
    build:
      context: .
      dockerfile: devopsloft/web/Dockerfile
      args:
        WEB_PORT: ${WEB_PORT}
        WEB_SECURE_PORT: ${WEB_SECURE_PORT}
        APP_PORT: ${APP_PORT}
        SERVER_NAME: ${SERVER_NAME}
    container_name: web
    environment:
      - SERVICE_NAME=web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_SECURE_PORT}:${WEB_SECURE_PORT}
    volumes:
      - certs:/etc/letsencrypt
      - www:/var/www/certbot
    links:
      - app
    restart: always

volumes:
  certs:
    external: true
  www:
    external: true
