name: Docker

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build spinner image
        run: docker build -t devopsloft/spinner .

      - name: Build application images
        run: docker-compose build
        
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u lioramilbaum --password-stdin

      - name: Push images
        run: |
          docker push devopsloft/spinner
          docker-compose push
