name: Docker

on:
  push:
    branches:
      - master

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build
        
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u lioramilbaum --password-stdin

      - name: Push image
        run: |
          docker-compose push
